#!/bin/sh
# Helper script to save Hytale server authentication tokens for persistence across restarts
# 
# Usage:
#   1. Authenticate in the server console: /auth login device
#   2. Check status: /auth status
#   3. Run this script and paste the tokens when prompted
#   4. Tokens will auto-load on next restart

set -eu

DATA_DIR="${DATA_DIR:-/home/container}"
TOKENS_FILE="${DATA_DIR}/.hytale-server-tokens"

echo "=== Hytale Server Token Persistence Helper ==="
echo ""
echo "This script will save your server authentication tokens so they"
echo "persist across container restarts."
echo ""
echo "First, authenticate your server:"
echo "  1. In server console, run: /auth login device"
echo "  2. Follow the authentication steps"
echo "  3. Run: /auth status"
echo "  4. Copy the Session Token and Identity Token"
echo ""
echo "Enter your tokens below (they will be hidden for security):"
echo ""

# Read session token
printf "Session Token: "
stty -echo 2>/dev/null || true
read -r SESSION_TOKEN
stty echo 2>/dev/null || true
echo ""

# Read identity token
printf "Identity Token: "
stty -echo 2>/dev/null || true
read -r IDENTITY_TOKEN
stty echo 2>/dev/null || true
echo ""
echo ""

# Validate tokens aren't empty
if [ -z "${SESSION_TOKEN}" ] || [ -z "${IDENTITY_TOKEN}" ]; then
  echo "ERROR: Both tokens are required. Please try again."
  exit 1
fi

# Save tokens to file
{
  echo "# Hytale Server Authentication Tokens"
  echo "# Auto-generated by save-auth-tokens.sh"
  echo "# These tokens will be automatically loaded on container start"
  echo "session_token=${SESSION_TOKEN}"
  echo "identity_token=${IDENTITY_TOKEN}"
} > "${TOKENS_FILE}"

chmod 600 "${TOKENS_FILE}" 2>/dev/null || true

echo "✓ Tokens saved to ${TOKENS_FILE}"
echo ""
echo "Your server will now automatically authenticate on restart!"
echo ""
echo "Note: Tokens may expire after some time. If authentication fails,"
echo "re-run /auth login and this script to refresh them."
